/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package br.com.examefacil.swing;

import br.com.examefacil.controller.PacienteControl;
import br.com.examefacil.tools.Util;

/**
 *
 * @author bruno
 */
public class DialogBuscarUsuarioFacebook extends javax.swing.JDialog {
    
    TelaPaciente telaPaciente;
    /**
     * Creates new form DialogBuscarUsuarioFacebook
     */
    public DialogBuscarUsuarioFacebook(java.awt.Frame parent, boolean modal, TelaPaciente telaPaciente) {
        super(parent, modal);
        initComponents();
        this.telaPaciente = telaPaciente;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtBuscaPacienteFB = new javax.swing.JTextField();
        jBtnBuscaPacienteFB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblPacientesFB = new javax.swing.JTable();
        jBtnSelecionaPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar perfil do Facebook");

        jBtnBuscaPacienteFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pesquisar.png"))); // NOI18N
        jBtnBuscaPacienteFB.setText("Buscar");
        jBtnBuscaPacienteFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscaPacienteFBActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do paciente:");

        jTblPacientesFB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblPacientesFB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTblPacientesFBMouseMoved(evt);
            }
        });
        jTblPacientesFB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblPacientesFBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblPacientesFB);

        jBtnSelecionaPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gravar.png"))); // NOI18N
        jBtnSelecionaPerfil.setText("Selecionar perfil");
        jBtnSelecionaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelecionaPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtBuscaPacienteFB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnBuscaPacienteFB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnSelecionaPerfil)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTxtBuscaPacienteFB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jBtnBuscaPacienteFB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSelecionaPerfil)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscaPacienteFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscaPacienteFBActionPerformed
        new PacienteControl().buscaPacientesFB(jTxtBuscaPacienteFB.getText(), jTblPacientesFB);
    }//GEN-LAST:event_jBtnBuscaPacienteFBActionPerformed

    private void jBtnSelecionaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelecionaPerfilActionPerformed
        if(jTblPacientesFB.getSelectedRow()>-1){
            new PacienteControl().selecionarPerfil(jTblPacientesFB.getSelectedRow(), jTblPacientesFB, telaPaciente);
            this.dispose();
        } else {
            Util.Aviso("Selecione um perfil");
        }
    }//GEN-LAST:event_jBtnSelecionaPerfilActionPerformed

    private void jTblPacientesFBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblPacientesFBMouseMoved
        
    }//GEN-LAST:event_jTblPacientesFBMouseMoved

    private void jTblPacientesFBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblPacientesFBMouseClicked
        if (evt.getClickCount() == 2) {
            int selected = jTblPacientesFB.getSelectedRow();
            String uri = "https://fb.com/"+jTblPacientesFB.getModel().getValueAt(selected, 2);
            new Util().openWebpage(uri);
        }
    }//GEN-LAST:event_jTblPacientesFBMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscaPacienteFB;
    private javax.swing.JButton jBtnSelecionaPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblPacientesFB;
    private javax.swing.JTextField jTxtBuscaPacienteFB;
    // End of variables declaration//GEN-END:variables
}
